apiVersion: v1
kind: Service
metadata:
  name: {{jobName}}
spec:
  ports:
    - protocol: "TCP"
      port: {{port}}        # The port inside the cluster
      targetPort: 80  # The port exposed by the service
  type: NodePort        # Type of service
  selector:
    app: {{jobName}}